INSERT INTO ROLES (
	ID, 
	CREATED_AT, 
	LAST_MODIFIED_AT, 
	NAME
) VALUES (
	UNHEX(REPLACE(UUID(), '-', '')), 
	CURRENT_TIMESTAMP,
	NULL,
	'Customer'
);

INSERT INTO ROLES (
	ID, 
	CREATED_AT, 
	LAST_MODIFIED_AT, 
	NAME
) VALUES (
	UNHEX(REPLACE(UUID(), '-', '')), 
	CURRENT_TIMESTAMP,
	NULL,
	'Employee'
);

INSERT INTO USERS (
	ID,
	FIRST_NAME,
	LAST_NAME,
	CREATED_AT,
	LAST_MODIFIED_AT,
	EMAIL,
	LOCKED,
	PASSWORD,
	USERNAME,
	EMAIL_CONFIRMED
) VALUES (
	UNHEX(REPLACE(UUID(), '-', '')),
	'John',
	'Doe',
	CURRENT_TIMESTAMP,
	NULL,
	'john.doe@bookify.com',
	0,
	'$2a$10$rtso7kYOpaWDdAgT51eMMemZAnXWVGUUAIoQF6Lp3kqSKpLQ9Tk2u', -- employee123#1
	'john.doe',
	1
);

INSERT INTO USER_ROLE_MAP (
	USER_ID,
	ROLE_ID
) VALUES (
	(SELECT ID FROM USERS WHERE USERNAME = 'john.doe'),
	(SELECT ID FROM ROLES WHERE NAME = 'Employee')
);